name: cooperator
version: 0.1.0.0
github: "aghoneim92"
license: MIT
author: "Ahmed Ghoneim"
maintainer: "ahmedghoneim92@gmail.com"
copyright: "2018 Ahmed Ghoneim"

extra-source-files:
  - README.md
  - ChangeLog.md

  # Metadata used when publishing your package
  # synopsis:            Short description of your package
  # category:            Web

  # To avoid duplicated efforts in documentation and dealing with the
  # complications of embedding Haddock markup inside cabal files, it is
  # common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cooperator#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Cooperator

executables:
  cooperator-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cooperator

tests:
  cooperator-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cooperator
      - hspec >= 2.0
      - QuickCheck
      - HUnit >= 1.0
    build-tools: hspec-discover
